- code_review:
    name: 'Code Review'
    count: 1
    users:
      - aterris
      - rmody
      - dreyks
- mission_control_admin:
    name: 'Mission Control Config Changes'
    users:
      - aterris
    paths:
      - '.mission-control.yml'